swagger: "2.0"
info:
  version: "2.1.2"
  title: "Transaction API"
  description: "API pour enregistrer, afficher et importer des transactions"
  termsOfService: "https://swagger.io/terms/"
  contact:
    email: "support@swagger.io"
host: "localhost:5000"
basePath: "/"
schemes:
  - "http"
paths:
  /add:
    post:
      tags:
        - "Transaction"
      summary: "Enregistrer une transaction"
      description: "Enregistrer une transaction entre deux personnes à une certaine date et pour une certaine valeur"
      operationId: "addTransaction"
      parameters:
        - in: "body"
          name: "body"
          description: "Transaction à enregistrer"
          required: true
          schema:
            type: "object"
            properties:
              P1:
                type: "object"
                properties:
                  firstname:
                    type: "string"
                  name:
                    type: "string"
              P2:
                type: "object"
                properties:
                  firstname:
                    type: "string"
                  name:
                    type: "string"
              date:
                type: "string"
                format: "date"
              value:
                type: "integer"
      responses:
        200:
          description: "Transaction enregistrée avec succès"
          schema:
            type: "object"
            properties:
              P1:
                type: "object"
                properties:
                  firstname:
                    type: "string"
                  name:
                    type: "string"
              P2:
                type: "object"
                properties:
                  firstname:
                    type: "string"
                  name:
                    type: "string"
              date:
                type: "string"
                format: "date"
              value:
                type: "integer"
        400:
          description: "Erreur dans la requête"

  /list:
    get:
      tags:
        - "Transaction"
      summary: "Afficher une liste de toutes les transactions"
      description: "Afficher une liste de toutes les transactions dans l'ordre chronologique"
      operationId: "getTransactionList"
      responses:
        200:
          description: "Liste de transactions"
          schema:
            type: "array"
            items:
              type: "object"
              properties:
                from:
                  type: "string"
                to:
                  type: "string"
                date:
                  type: "string"
                  format: "date"
                amount:
                  type: "integer"
        400:
          description: "Erreur dans la requête"

  /transactions/{person_id}:
    get:
      description: "Afficher une liste de toutes les transactions dans l’ordre chronologique liées à une personne"
      parameters:
        - name: "person_id"
          in: "path"
          required: true
          description: "ID de la personne"
          type: "integer"
      responses:
        200:
          description: "Liste des transactions triées dans l’ordre chronologique pour une personne"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  type: "object"
                  properties:
                    from:
                      type: "string"
                      description: "Nom de la personne qui a effectué la transaction"
                    to:
                      type: "string"
                      description: "Nom de la personne à qui la transaction a été effectuée"
                    date:
                      type: "string"
                      format: "date-time"
                      description: "Date de la transaction"
                    amount:
                      type: "number"
                      description: "Montant de la transaction"
        400:
          description: "Erreur dans la requête"

  /solde/{id}:
    get:
      description: "Afficher le solde du compte de la personne"
      parameters:
        - in: "path"
          name: "id"
          schema:
            type: "integer"
          required: true
          description: "ID de la personne"
      responses:
        200:
          description: "Information sur le solde du compte"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  id:
                    type: "integer"
                  firstname:
                    type: "string"
                  name:
                    type: "string"
                  solde:
                    type: "integer"
        404:
          description: "La personne est introuvable"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  error:
                    type: "string"

