name: Flask app build

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Flask app build
      run: |
        python -m pip install -r requirements.txt
        python TP.py check_syntax
